# common vars
:url = http://127.0.0.1:9000/api/v1

:HEADER = <<
Content-Type: application/json
x-auth: 9ed37157-b8a7-46c1-89fb-1cc3b09d1a85
#

# auth
## login
POST :url/user/login
content-type: application/json

{
	"Username" : "admin",
	"Password" : "admin"
}

## logout
POST :url/user/logout
:HEADER

# products
## get all products
GET :url/product
:HEADER

## create new product
POST :url/product
:HEADER

{
  "Product": {
    "Price": 1299,
    "Name": "čižme",
    "Description": "zakon stvar za vrt\n<h1>I za hodanje po kisi i grmljavini</h1>",
    "ImagePath": "http://www.publicdomainpictures.net/pictures/110000/nahled/cowboy-boots-1416282316H1J.jpg"
  },
  "Images": [
    "c3RyaW5nMQ==",
    "c3RyaW5nMg==",
    "aW1hZ2Uw"
  ]
}

## delete product
DELETE :url/product/7
:HEADER

## update product
PUT :url/product/2
:HEADER
{
	"Price" : 100,
	"Name" : "čižme",
	"Description" : "zakon stvar za vrt",
}

# news
## get all news
GET :url/news
:HEADER

## create news
POST :url/news
:HEADER

{
  "News": {
    "Header": "naslov 2",
    "Text": "ovo je neki super kuul text o necemu totalno nebitnom"
  },
  "Image": "c3RyaW5nMQ=="
}

## delete news
DELETE :url/news/3
:HEADER

## update news
PUT :url/news/1
:HEADER

{
  "News": {
    "Header": "naslov 1",
    "Text": "ovo je neki super kuul text o necemu totalno nebitnom"
  },
  "Image": "c3RyaW5nMQ=="
}

  #aW1hZ2Uw
  #c3RyaW5nMQ==