# get all products

GET http://localhost:8080/products


# create new product

POST http://localhost:8080/products
Content-Type: application/json

{
	"Price": 100.25,
	"Name": "čižme",
	"Description": "zakon stvar za vrt"
}
